apiVersion: v1
kind: Service
metadata:
  name: brightship-notify
  namespace: brightship
spec:
  selector:
    app: brightship-notify
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
