apiVersion: apps/v1
kind: Deployment
metadata:
  name: brightship-jobs
  namespace: brightship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brightship-jobs
  template:
    metadata:
      labels:
        app: brightship-jobs
    spec:
      containers:
        - name: brightship-jobs
          image: ghcr.io/dreyshantel/brightship-jobs:89d06c768add64f6436944f93eaeee2efe1383ae
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: brightship-jobs-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
